networks:
  weather_grid_service_net:

services:
  app:
    container_name: weather_grid_service_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9778:9778"
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - weather_grid_service_net

  db:
    container_name: weather_grid_service_db
    platform: linux/amd64
    image: kartoza/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/weather_grid_service
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: weather_grid_service
    ports:
      - "9876:5432"
    volumes:
      - ./data_db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 100m
    networks:
      - weather_grid_service_net

  redis:
    container_name: weather_grid_service_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data_redis:/data
    networks:
      - weather_grid_service_net