server:
  port: 9778
spring:
  datasource:
    url: jdbc:postgresql://localhost:9876/weather_grid_service
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: ERROR
    liquibase: ERROR
    org.springframework.security: ERROR
  logback:
    rolling policy:
      max-history: 5
      max-file-size: 10MB