server:
  port: 9788
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:9876/weather_grid_service
    username: qwe
    password: qwe
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cache:
    type: redis
    cache-names: forecast
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: ERROR
    liquibase: ERROR
    org.springframework.security: ERROR
    org.springframework.cache: DEBUG
    org.springframework.boot.context.config: DEBUG
  logback:
    rolling policy:
      max-history: 5
      max-file-size: 10MB